/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GtrRouteRouteImport } from './routes/gtr/route'
import { Route as ApiAfishaRouteImport } from './routes/api.afisha'
import { Route as ApiAfishaSendRouteImport } from './routes/api.afisha-send'
import { Route as ApiAphotoRouteImport } from './routes/api.aphoto'
import { Route as ApiAvideoRouteImport } from './routes/api.avideo'
import { Route as ApiBossHeadRouteImport } from './routes/api.boss-head'
import { Route as ApiBroLearnRouteImport } from './routes/api.bro-learn'
import { Route as ApiCommunityDigestRouteImport } from './routes/api.community-digest'
import { Route as ApiGtrBroGemRouteImport } from './routes/api.gtr-bro-gem'
import { Route as ApiGtrBroGemtestRouteImport } from './routes/api.gtr-bro-gemtest'
import { Route as ApiGtrBroSdpRouteImport } from './routes/api.gtr-bro-sdp'
import { Route as ApiGtrBroSessionRouteImport } from './routes/api.gtr-bro-session'
import { Route as ApiGtrBroTextRouteImport } from './routes/api.gtr-bro-text'
import { Route as ApiGtrBroToolRouteImport } from './routes/api.gtr-bro-tool'
import { Route as ApiPosterRouteImport } from './routes/api.poster'
import { Route as ApiPushRouteImport } from './routes/api.push'
import { Route as ApiSpotifyCallbackRouteImport } from './routes/api.spotify-callback'
import { Route as ApiSpotifyLoginRouteImport } from './routes/api.spotify-login'
import { Route as ApiSprintReportRouteImport } from './routes/api.sprint-report'
import { Route as ApiTgRouteImport } from './routes/api.tg'
import { Route as ApiVillaCheckRouteImport } from './routes/api.villa-check'
import { Route as ApiVphotoRouteImport } from './routes/api.vphoto'
import { Route as GtrIndexRouteImport } from './routes/gtr/index'
import { Route as GtrScreenRouteImport } from './routes/gtr/$screen'
import { Route as GtrJoinRouteImport } from './routes/gtr/join'
import { Route as GtrLoginRouteImport } from './routes/gtr/login'
import { Route as GtrOrganizerRouteImport } from './routes/gtr/organizer'
import { Route as GtrSignupRouteImport } from './routes/gtr/signup'
import { Route as GtrVRouteImport } from './routes/gtr/v'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GtrRouteRoute = GtrRouteRouteImport.update({
  id: '/gtr',
  path: '/gtr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAfishaRoute = ApiAfishaRouteImport.update({
  id: '/api/afisha',
  path: '/api/afisha',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAfishaSendRoute = ApiAfishaSendRouteImport.update({
  id: '/api/afisha-send',
  path: '/api/afisha-send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAphotoRoute = ApiAphotoRouteImport.update({
  id: '/api/aphoto',
  path: '/api/aphoto',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvideoRoute = ApiAvideoRouteImport.update({
  id: '/api/avideo',
  path: '/api/avideo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBossHeadRoute = ApiBossHeadRouteImport.update({
  id: '/api/boss-head',
  path: '/api/boss-head',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBroLearnRoute = ApiBroLearnRouteImport.update({
  id: '/api/bro-learn',
  path: '/api/bro-learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommunityDigestRoute = ApiCommunityDigestRouteImport.update({
  id: '/api/community-digest',
  path: '/api/community-digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGtrBroGemRoute = ApiGtrBroGemRouteImport.update({
  id: '/api/gtr-bro-gem',
  path: '/api/gtr-bro-gem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGtrBroGemtestRoute = ApiGtrBroGemtestRouteImport.update({
  id: '/api/gtr-bro-gemtest',
  path: '/api/gtr-bro-gemtest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGtrBroSdpRoute = ApiGtrBroSdpRouteImport.update({
  id: '/api/gtr-bro-sdp',
  path: '/api/gtr-bro-sdp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGtrBroSessionRoute = ApiGtrBroSessionRouteImport.update({
  id: '/api/gtr-bro-session',
  path: '/api/gtr-bro-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGtrBroTextRoute = ApiGtrBroTextRouteImport.update({
  id: '/api/gtr-bro-text',
  path: '/api/gtr-bro-text',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGtrBroToolRoute = ApiGtrBroToolRouteImport.update({
  id: '/api/gtr-bro-tool',
  path: '/api/gtr-bro-tool',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPosterRoute = ApiPosterRouteImport.update({
  id: '/api/poster',
  path: '/api/poster',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushRoute = ApiPushRouteImport.update({
  id: '/api/push',
  path: '/api/push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyCallbackRoute = ApiSpotifyCallbackRouteImport.update({
  id: '/api/spotify-callback',
  path: '/api/spotify-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyLoginRoute = ApiSpotifyLoginRouteImport.update({
  id: '/api/spotify-login',
  path: '/api/spotify-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSprintReportRoute = ApiSprintReportRouteImport.update({
  id: '/api/sprint-report',
  path: '/api/sprint-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTgRoute = ApiTgRouteImport.update({
  id: '/api/tg',
  path: '/api/tg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVillaCheckRoute = ApiVillaCheckRouteImport.update({
  id: '/api/villa-check',
  path: '/api/villa-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVphotoRoute = ApiVphotoRouteImport.update({
  id: '/api/vphoto',
  path: '/api/vphoto',
  getParentRoute: () => rootRouteImport,
} as any)
const GtrIndexRoute = GtrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GtrRouteRoute,
} as any)
const GtrScreenRoute = GtrScreenRouteImport.update({
  id: '/$screen',
  path: '/$screen',
  getParentRoute: () => GtrRouteRoute,
} as any)
const GtrJoinRoute = GtrJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => GtrRouteRoute,
} as any)
const GtrLoginRoute = GtrLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GtrRouteRoute,
} as any)
const GtrOrganizerRoute = GtrOrganizerRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => GtrRouteRoute,
} as any)
const GtrSignupRoute = GtrSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GtrRouteRoute,
} as any)
const GtrVRoute = GtrVRouteImport.update({
  id: '/v',
  path: '/v',
  getParentRoute: () => GtrRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gtr': typeof GtrRouteRouteWithChildren
  '/api/afisha': typeof ApiAfishaRoute
  '/api/afisha-send': typeof ApiAfishaSendRoute
  '/api/aphoto': typeof ApiAphotoRoute
  '/api/avideo': typeof ApiAvideoRoute
  '/api/boss-head': typeof ApiBossHeadRoute
  '/api/bro-learn': typeof ApiBroLearnRoute
  '/api/community-digest': typeof ApiCommunityDigestRoute
  '/api/gtr-bro-gem': typeof ApiGtrBroGemRoute
  '/api/gtr-bro-gemtest': typeof ApiGtrBroGemtestRoute
  '/api/gtr-bro-sdp': typeof ApiGtrBroSdpRoute
  '/api/gtr-bro-session': typeof ApiGtrBroSessionRoute
  '/api/gtr-bro-text': typeof ApiGtrBroTextRoute
  '/api/gtr-bro-tool': typeof ApiGtrBroToolRoute
  '/api/poster': typeof ApiPosterRoute
  '/api/push': typeof ApiPushRoute
  '/api/spotify-callback': typeof ApiSpotifyCallbackRoute
  '/api/spotify-login': typeof ApiSpotifyLoginRoute
  '/api/sprint-report': typeof ApiSprintReportRoute
  '/api/tg': typeof ApiTgRoute
  '/api/villa-check': typeof ApiVillaCheckRoute
  '/api/vphoto': typeof ApiVphotoRoute
  '/gtr/$screen': typeof GtrScreenRoute
  '/gtr/join': typeof GtrJoinRoute
  '/gtr/login': typeof GtrLoginRoute
  '/gtr/organizer': typeof GtrOrganizerRoute
  '/gtr/signup': typeof GtrSignupRoute
  '/gtr/v': typeof GtrVRoute
  '/gtr/': typeof GtrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/afisha': typeof ApiAfishaRoute
  '/api/afisha-send': typeof ApiAfishaSendRoute
  '/api/aphoto': typeof ApiAphotoRoute
  '/api/avideo': typeof ApiAvideoRoute
  '/api/boss-head': typeof ApiBossHeadRoute
  '/api/bro-learn': typeof ApiBroLearnRoute
  '/api/community-digest': typeof ApiCommunityDigestRoute
  '/api/gtr-bro-gem': typeof ApiGtrBroGemRoute
  '/api/gtr-bro-gemtest': typeof ApiGtrBroGemtestRoute
  '/api/gtr-bro-sdp': typeof ApiGtrBroSdpRoute
  '/api/gtr-bro-session': typeof ApiGtrBroSessionRoute
  '/api/gtr-bro-text': typeof ApiGtrBroTextRoute
  '/api/gtr-bro-tool': typeof ApiGtrBroToolRoute
  '/api/poster': typeof ApiPosterRoute
  '/api/push': typeof ApiPushRoute
  '/api/spotify-callback': typeof ApiSpotifyCallbackRoute
  '/api/spotify-login': typeof ApiSpotifyLoginRoute
  '/api/sprint-report': typeof ApiSprintReportRoute
  '/api/tg': typeof ApiTgRoute
  '/api/villa-check': typeof ApiVillaCheckRoute
  '/api/vphoto': typeof ApiVphotoRoute
  '/gtr/$screen': typeof GtrScreenRoute
  '/gtr/join': typeof GtrJoinRoute
  '/gtr/login': typeof GtrLoginRoute
  '/gtr/organizer': typeof GtrOrganizerRoute
  '/gtr/signup': typeof GtrSignupRoute
  '/gtr/v': typeof GtrVRoute
  '/gtr': typeof GtrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gtr': typeof GtrRouteRouteWithChildren
  '/api/afisha': typeof ApiAfishaRoute
  '/api/afisha-send': typeof ApiAfishaSendRoute
  '/api/aphoto': typeof ApiAphotoRoute
  '/api/avideo': typeof ApiAvideoRoute
  '/api/boss-head': typeof ApiBossHeadRoute
  '/api/bro-learn': typeof ApiBroLearnRoute
  '/api/community-digest': typeof ApiCommunityDigestRoute
  '/api/gtr-bro-gem': typeof ApiGtrBroGemRoute
  '/api/gtr-bro-gemtest': typeof ApiGtrBroGemtestRoute
  '/api/gtr-bro-sdp': typeof ApiGtrBroSdpRoute
  '/api/gtr-bro-session': typeof ApiGtrBroSessionRoute
  '/api/gtr-bro-text': typeof ApiGtrBroTextRoute
  '/api/gtr-bro-tool': typeof ApiGtrBroToolRoute
  '/api/poster': typeof ApiPosterRoute
  '/api/push': typeof ApiPushRoute
  '/api/spotify-callback': typeof ApiSpotifyCallbackRoute
  '/api/spotify-login': typeof ApiSpotifyLoginRoute
  '/api/sprint-report': typeof ApiSprintReportRoute
  '/api/tg': typeof ApiTgRoute
  '/api/villa-check': typeof ApiVillaCheckRoute
  '/api/vphoto': typeof ApiVphotoRoute
  '/gtr/$screen': typeof GtrScreenRoute
  '/gtr/join': typeof GtrJoinRoute
  '/gtr/login': typeof GtrLoginRoute
  '/gtr/organizer': typeof GtrOrganizerRoute
  '/gtr/signup': typeof GtrSignupRoute
  '/gtr/v': typeof GtrVRoute
  '/gtr/': typeof GtrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gtr'
    | '/api/afisha'
    | '/api/afisha-send'
    | '/api/aphoto'
    | '/api/avideo'
    | '/api/boss-head'
    | '/api/bro-learn'
    | '/api/community-digest'
    | '/api/gtr-bro-gem'
    | '/api/gtr-bro-gemtest'
    | '/api/gtr-bro-sdp'
    | '/api/gtr-bro-session'
    | '/api/gtr-bro-text'
    | '/api/gtr-bro-tool'
    | '/api/poster'
    | '/api/push'
    | '/api/spotify-callback'
    | '/api/spotify-login'
    | '/api/sprint-report'
    | '/api/tg'
    | '/api/villa-check'
    | '/api/vphoto'
    | '/gtr/$screen'
    | '/gtr/join'
    | '/gtr/login'
    | '/gtr/organizer'
    | '/gtr/signup'
    | '/gtr/v'
    | '/gtr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/afisha'
    | '/api/afisha-send'
    | '/api/aphoto'
    | '/api/avideo'
    | '/api/boss-head'
    | '/api/bro-learn'
    | '/api/community-digest'
    | '/api/gtr-bro-gem'
    | '/api/gtr-bro-gemtest'
    | '/api/gtr-bro-sdp'
    | '/api/gtr-bro-session'
    | '/api/gtr-bro-text'
    | '/api/gtr-bro-tool'
    | '/api/poster'
    | '/api/push'
    | '/api/spotify-callback'
    | '/api/spotify-login'
    | '/api/sprint-report'
    | '/api/tg'
    | '/api/villa-check'
    | '/api/vphoto'
    | '/gtr/$screen'
    | '/gtr/join'
    | '/gtr/login'
    | '/gtr/organizer'
    | '/gtr/signup'
    | '/gtr/v'
    | '/gtr'
  id:
    | '__root__'
    | '/'
    | '/gtr'
    | '/api/afisha'
    | '/api/afisha-send'
    | '/api/aphoto'
    | '/api/avideo'
    | '/api/boss-head'
    | '/api/bro-learn'
    | '/api/community-digest'
    | '/api/gtr-bro-gem'
    | '/api/gtr-bro-gemtest'
    | '/api/gtr-bro-sdp'
    | '/api/gtr-bro-session'
    | '/api/gtr-bro-text'
    | '/api/gtr-bro-tool'
    | '/api/poster'
    | '/api/push'
    | '/api/spotify-callback'
    | '/api/spotify-login'
    | '/api/sprint-report'
    | '/api/tg'
    | '/api/villa-check'
    | '/api/vphoto'
    | '/gtr/$screen'
    | '/gtr/join'
    | '/gtr/login'
    | '/gtr/organizer'
    | '/gtr/signup'
    | '/gtr/v'
    | '/gtr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GtrRouteRoute: typeof GtrRouteRouteWithChildren
  ApiAfishaRoute: typeof ApiAfishaRoute
  ApiAfishaSendRoute: typeof ApiAfishaSendRoute
  ApiAphotoRoute: typeof ApiAphotoRoute
  ApiAvideoRoute: typeof ApiAvideoRoute
  ApiBossHeadRoute: typeof ApiBossHeadRoute
  ApiBroLearnRoute: typeof ApiBroLearnRoute
  ApiCommunityDigestRoute: typeof ApiCommunityDigestRoute
  ApiGtrBroGemRoute: typeof ApiGtrBroGemRoute
  ApiGtrBroGemtestRoute: typeof ApiGtrBroGemtestRoute
  ApiGtrBroSdpRoute: typeof ApiGtrBroSdpRoute
  ApiGtrBroSessionRoute: typeof ApiGtrBroSessionRoute
  ApiGtrBroTextRoute: typeof ApiGtrBroTextRoute
  ApiGtrBroToolRoute: typeof ApiGtrBroToolRoute
  ApiPosterRoute: typeof ApiPosterRoute
  ApiPushRoute: typeof ApiPushRoute
  ApiSpotifyCallbackRoute: typeof ApiSpotifyCallbackRoute
  ApiSpotifyLoginRoute: typeof ApiSpotifyLoginRoute
  ApiSprintReportRoute: typeof ApiSprintReportRoute
  ApiTgRoute: typeof ApiTgRoute
  ApiVillaCheckRoute: typeof ApiVillaCheckRoute
  ApiVphotoRoute: typeof ApiVphotoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gtr': {
      id: '/gtr'
      path: '/gtr'
      fullPath: '/gtr'
      preLoaderRoute: typeof GtrRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/afisha': {
      id: '/api/afisha'
      path: '/api/afisha'
      fullPath: '/api/afisha'
      preLoaderRoute: typeof ApiAfishaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/afisha-send': {
      id: '/api/afisha-send'
      path: '/api/afisha-send'
      fullPath: '/api/afisha-send'
      preLoaderRoute: typeof ApiAfishaSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/aphoto': {
      id: '/api/aphoto'
      path: '/api/aphoto'
      fullPath: '/api/aphoto'
      preLoaderRoute: typeof ApiAphotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avideo': {
      id: '/api/avideo'
      path: '/api/avideo'
      fullPath: '/api/avideo'
      preLoaderRoute: typeof ApiAvideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/boss-head': {
      id: '/api/boss-head'
      path: '/api/boss-head'
      fullPath: '/api/boss-head'
      preLoaderRoute: typeof ApiBossHeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bro-learn': {
      id: '/api/bro-learn'
      path: '/api/bro-learn'
      fullPath: '/api/bro-learn'
      preLoaderRoute: typeof ApiBroLearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/community-digest': {
      id: '/api/community-digest'
      path: '/api/community-digest'
      fullPath: '/api/community-digest'
      preLoaderRoute: typeof ApiCommunityDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gtr-bro-gem': {
      id: '/api/gtr-bro-gem'
      path: '/api/gtr-bro-gem'
      fullPath: '/api/gtr-bro-gem'
      preLoaderRoute: typeof ApiGtrBroGemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gtr-bro-gemtest': {
      id: '/api/gtr-bro-gemtest'
      path: '/api/gtr-bro-gemtest'
      fullPath: '/api/gtr-bro-gemtest'
      preLoaderRoute: typeof ApiGtrBroGemtestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gtr-bro-sdp': {
      id: '/api/gtr-bro-sdp'
      path: '/api/gtr-bro-sdp'
      fullPath: '/api/gtr-bro-sdp'
      preLoaderRoute: typeof ApiGtrBroSdpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gtr-bro-session': {
      id: '/api/gtr-bro-session'
      path: '/api/gtr-bro-session'
      fullPath: '/api/gtr-bro-session'
      preLoaderRoute: typeof ApiGtrBroSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gtr-bro-text': {
      id: '/api/gtr-bro-text'
      path: '/api/gtr-bro-text'
      fullPath: '/api/gtr-bro-text'
      preLoaderRoute: typeof ApiGtrBroTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gtr-bro-tool': {
      id: '/api/gtr-bro-tool'
      path: '/api/gtr-bro-tool'
      fullPath: '/api/gtr-bro-tool'
      preLoaderRoute: typeof ApiGtrBroToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/poster': {
      id: '/api/poster'
      path: '/api/poster'
      fullPath: '/api/poster'
      preLoaderRoute: typeof ApiPosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push': {
      id: '/api/push'
      path: '/api/push'
      fullPath: '/api/push'
      preLoaderRoute: typeof ApiPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify-callback': {
      id: '/api/spotify-callback'
      path: '/api/spotify-callback'
      fullPath: '/api/spotify-callback'
      preLoaderRoute: typeof ApiSpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify-login': {
      id: '/api/spotify-login'
      path: '/api/spotify-login'
      fullPath: '/api/spotify-login'
      preLoaderRoute: typeof ApiSpotifyLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sprint-report': {
      id: '/api/sprint-report'
      path: '/api/sprint-report'
      fullPath: '/api/sprint-report'
      preLoaderRoute: typeof ApiSprintReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tg': {
      id: '/api/tg'
      path: '/api/tg'
      fullPath: '/api/tg'
      preLoaderRoute: typeof ApiTgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/villa-check': {
      id: '/api/villa-check'
      path: '/api/villa-check'
      fullPath: '/api/villa-check'
      preLoaderRoute: typeof ApiVillaCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vphoto': {
      id: '/api/vphoto'
      path: '/api/vphoto'
      fullPath: '/api/vphoto'
      preLoaderRoute: typeof ApiVphotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gtr/': {
      id: '/gtr/'
      path: '/'
      fullPath: '/gtr/'
      preLoaderRoute: typeof GtrIndexRouteImport
      parentRoute: typeof GtrRouteRoute
    }
    '/gtr/$screen': {
      id: '/gtr/$screen'
      path: '/$screen'
      fullPath: '/gtr/$screen'
      preLoaderRoute: typeof GtrScreenRouteImport
      parentRoute: typeof GtrRouteRoute
    }
    '/gtr/join': {
      id: '/gtr/join'
      path: '/join'
      fullPath: '/gtr/join'
      preLoaderRoute: typeof GtrJoinRouteImport
      parentRoute: typeof GtrRouteRoute
    }
    '/gtr/login': {
      id: '/gtr/login'
      path: '/login'
      fullPath: '/gtr/login'
      preLoaderRoute: typeof GtrLoginRouteImport
      parentRoute: typeof GtrRouteRoute
    }
    '/gtr/organizer': {
      id: '/gtr/organizer'
      path: '/organizer'
      fullPath: '/gtr/organizer'
      preLoaderRoute: typeof GtrOrganizerRouteImport
      parentRoute: typeof GtrRouteRoute
    }
    '/gtr/signup': {
      id: '/gtr/signup'
      path: '/signup'
      fullPath: '/gtr/signup'
      preLoaderRoute: typeof GtrSignupRouteImport
      parentRoute: typeof GtrRouteRoute
    }
    '/gtr/v': {
      id: '/gtr/v'
      path: '/v'
      fullPath: '/gtr/v'
      preLoaderRoute: typeof GtrVRouteImport
      parentRoute: typeof GtrRouteRoute
    }
  }
}

interface GtrRouteRouteChildren {
  GtrScreenRoute: typeof GtrScreenRoute
  GtrJoinRoute: typeof GtrJoinRoute
  GtrLoginRoute: typeof GtrLoginRoute
  GtrOrganizerRoute: typeof GtrOrganizerRoute
  GtrSignupRoute: typeof GtrSignupRoute
  GtrVRoute: typeof GtrVRoute
  GtrIndexRoute: typeof GtrIndexRoute
}

const GtrRouteRouteChildren: GtrRouteRouteChildren = {
  GtrScreenRoute: GtrScreenRoute,
  GtrJoinRoute: GtrJoinRoute,
  GtrLoginRoute: GtrLoginRoute,
  GtrOrganizerRoute: GtrOrganizerRoute,
  GtrSignupRoute: GtrSignupRoute,
  GtrVRoute: GtrVRoute,
  GtrIndexRoute: GtrIndexRoute,
}

const GtrRouteRouteWithChildren = GtrRouteRoute._addFileChildren(
  GtrRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GtrRouteRoute: GtrRouteRouteWithChildren,
  ApiAfishaRoute: ApiAfishaRoute,
  ApiAfishaSendRoute: ApiAfishaSendRoute,
  ApiAphotoRoute: ApiAphotoRoute,
  ApiAvideoRoute: ApiAvideoRoute,
  ApiBossHeadRoute: ApiBossHeadRoute,
  ApiBroLearnRoute: ApiBroLearnRoute,
  ApiCommunityDigestRoute: ApiCommunityDigestRoute,
  ApiGtrBroGemRoute: ApiGtrBroGemRoute,
  ApiGtrBroGemtestRoute: ApiGtrBroGemtestRoute,
  ApiGtrBroSdpRoute: ApiGtrBroSdpRoute,
  ApiGtrBroSessionRoute: ApiGtrBroSessionRoute,
  ApiGtrBroTextRoute: ApiGtrBroTextRoute,
  ApiGtrBroToolRoute: ApiGtrBroToolRoute,
  ApiPosterRoute: ApiPosterRoute,
  ApiPushRoute: ApiPushRoute,
  ApiSpotifyCallbackRoute: ApiSpotifyCallbackRoute,
  ApiSpotifyLoginRoute: ApiSpotifyLoginRoute,
  ApiSprintReportRoute: ApiSprintReportRoute,
  ApiTgRoute: ApiTgRoute,
  ApiVillaCheckRoute: ApiVillaCheckRoute,
  ApiVphotoRoute: ApiVphotoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
