/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GtrRouteRouteImport } from './routes/gtr/route'
import { Route as ApiAfishaRouteImport } from './routes/api.afisha'
import { Route as ApiAfishaSendRouteImport } from './routes/api.afisha-send'
import { Route as ApiPosterRouteImport } from './routes/api.poster'
import { Route as ApiPushRouteImport } from './routes/api.push'
import { Route as ApiSprintReportRouteImport } from './routes/api.sprint-report'
import { Route as ApiTgRouteImport } from './routes/api.tg'
import { Route as ApiVphotoRouteImport } from './routes/api.vphoto'
import { Route as GtrIndexRouteImport } from './routes/gtr/index'
import { Route as GtrScreenRouteImport } from './routes/gtr/$screen'
import { Route as GtrJoinRouteImport } from './routes/gtr/join'
import { Route as GtrLoginRouteImport } from './routes/gtr/login'
import { Route as GtrOrganizerRouteImport } from './routes/gtr/organizer'
import { Route as GtrVRouteImport } from './routes/gtr/v'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GtrRouteRoute = GtrRouteRouteImport.update({
  id: '/gtr',
  path: '/gtr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAfishaRoute = ApiAfishaRouteImport.update({
  id: '/api/afisha',
  path: '/api/afisha',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAfishaSendRoute = ApiAfishaSendRouteImport.update({
  id: '/api/afisha-send',
  path: '/api/afisha-send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPosterRoute = ApiPosterRouteImport.update({
  id: '/api/poster',
  path: '/api/poster',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushRoute = ApiPushRouteImport.update({
  id: '/api/push',
  path: '/api/push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSprintReportRoute = ApiSprintReportRouteImport.update({
  id: '/api/sprint-report',
  path: '/api/sprint-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTgRoute = ApiTgRouteImport.update({
  id: '/api/tg',
  path: '/api/tg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVphotoRoute = ApiVphotoRouteImport.update({
  id: '/api/vphoto',
  path: '/api/vphoto',
  getParentRoute: () => rootRouteImport,
} as any)
const GtrIndexRoute = GtrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GtrRouteRoute,
} as any)
const GtrScreenRoute = GtrScreenRouteImport.update({
  id: '/$screen',
  path: '/$screen',
  getParentRoute: () => GtrRouteRoute,
} as any)
const GtrJoinRoute = GtrJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => GtrRouteRoute,
} as any)
const GtrLoginRoute = GtrLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GtrRouteRoute,
} as any)
const GtrOrganizerRoute = GtrOrganizerRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => GtrRouteRoute,
} as any)
const GtrVRoute = GtrVRouteImport.update({
  id: '/v',
  path: '/v',
  getParentRoute: () => GtrRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gtr': typeof GtrRouteRouteWithChildren
  '/api/afisha': typeof ApiAfishaRoute
  '/api/afisha-send': typeof ApiAfishaSendRoute
  '/api/poster': typeof ApiPosterRoute
  '/api/push': typeof ApiPushRoute
  '/api/sprint-report': typeof ApiSprintReportRoute
  '/api/tg': typeof ApiTgRoute
  '/api/vphoto': typeof ApiVphotoRoute
  '/gtr/$screen': typeof GtrScreenRoute
  '/gtr/join': typeof GtrJoinRoute
  '/gtr/login': typeof GtrLoginRoute
  '/gtr/organizer': typeof GtrOrganizerRoute
  '/gtr/v': typeof GtrVRoute
  '/gtr/': typeof GtrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/afisha': typeof ApiAfishaRoute
  '/api/afisha-send': typeof ApiAfishaSendRoute
  '/api/poster': typeof ApiPosterRoute
  '/api/push': typeof ApiPushRoute
  '/api/sprint-report': typeof ApiSprintReportRoute
  '/api/tg': typeof ApiTgRoute
  '/api/vphoto': typeof ApiVphotoRoute
  '/gtr/$screen': typeof GtrScreenRoute
  '/gtr/join': typeof GtrJoinRoute
  '/gtr/login': typeof GtrLoginRoute
  '/gtr/organizer': typeof GtrOrganizerRoute
  '/gtr/v': typeof GtrVRoute
  '/gtr': typeof GtrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gtr': typeof GtrRouteRouteWithChildren
  '/api/afisha': typeof ApiAfishaRoute
  '/api/afisha-send': typeof ApiAfishaSendRoute
  '/api/poster': typeof ApiPosterRoute
  '/api/push': typeof ApiPushRoute
  '/api/sprint-report': typeof ApiSprintReportRoute
  '/api/tg': typeof ApiTgRoute
  '/api/vphoto': typeof ApiVphotoRoute
  '/gtr/$screen': typeof GtrScreenRoute
  '/gtr/join': typeof GtrJoinRoute
  '/gtr/login': typeof GtrLoginRoute
  '/gtr/organizer': typeof GtrOrganizerRoute
  '/gtr/v': typeof GtrVRoute
  '/gtr/': typeof GtrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gtr'
    | '/api/afisha'
    | '/api/afisha-send'
    | '/api/poster'
    | '/api/push'
    | '/api/sprint-report'
    | '/api/tg'
    | '/api/vphoto'
    | '/gtr/$screen'
    | '/gtr/join'
    | '/gtr/login'
    | '/gtr/organizer'
    | '/gtr/v'
    | '/gtr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/afisha'
    | '/api/afisha-send'
    | '/api/poster'
    | '/api/push'
    | '/api/sprint-report'
    | '/api/tg'
    | '/api/vphoto'
    | '/gtr/$screen'
    | '/gtr/join'
    | '/gtr/login'
    | '/gtr/organizer'
    | '/gtr/v'
    | '/gtr'
  id:
    | '__root__'
    | '/'
    | '/gtr'
    | '/api/afisha'
    | '/api/afisha-send'
    | '/api/poster'
    | '/api/push'
    | '/api/sprint-report'
    | '/api/tg'
    | '/api/vphoto'
    | '/gtr/$screen'
    | '/gtr/join'
    | '/gtr/login'
    | '/gtr/organizer'
    | '/gtr/v'
    | '/gtr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GtrRouteRoute: typeof GtrRouteRouteWithChildren
  ApiAfishaRoute: typeof ApiAfishaRoute
  ApiAfishaSendRoute: typeof ApiAfishaSendRoute
  ApiPosterRoute: typeof ApiPosterRoute
  ApiPushRoute: typeof ApiPushRoute
  ApiSprintReportRoute: typeof ApiSprintReportRoute
  ApiTgRoute: typeof ApiTgRoute
  ApiVphotoRoute: typeof ApiVphotoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gtr': {
      id: '/gtr'
      path: '/gtr'
      fullPath: '/gtr'
      preLoaderRoute: typeof GtrRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/afisha': {
      id: '/api/afisha'
      path: '/api/afisha'
      fullPath: '/api/afisha'
      preLoaderRoute: typeof ApiAfishaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/afisha-send': {
      id: '/api/afisha-send'
      path: '/api/afisha-send'
      fullPath: '/api/afisha-send'
      preLoaderRoute: typeof ApiAfishaSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/poster': {
      id: '/api/poster'
      path: '/api/poster'
      fullPath: '/api/poster'
      preLoaderRoute: typeof ApiPosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push': {
      id: '/api/push'
      path: '/api/push'
      fullPath: '/api/push'
      preLoaderRoute: typeof ApiPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sprint-report': {
      id: '/api/sprint-report'
      path: '/api/sprint-report'
      fullPath: '/api/sprint-report'
      preLoaderRoute: typeof ApiSprintReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tg': {
      id: '/api/tg'
      path: '/api/tg'
      fullPath: '/api/tg'
      preLoaderRoute: typeof ApiTgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vphoto': {
      id: '/api/vphoto'
      path: '/api/vphoto'
      fullPath: '/api/vphoto'
      preLoaderRoute: typeof ApiVphotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gtr/': {
      id: '/gtr/'
      path: '/'
      fullPath: '/gtr/'
      preLoaderRoute: typeof GtrIndexRouteImport
      parentRoute: typeof GtrRouteRoute
    }
    '/gtr/$screen': {
      id: '/gtr/$screen'
      path: '/$screen'
      fullPath: '/gtr/$screen'
      preLoaderRoute: typeof GtrScreenRouteImport
      parentRoute: typeof GtrRouteRoute
    }
    '/gtr/join': {
      id: '/gtr/join'
      path: '/join'
      fullPath: '/gtr/join'
      preLoaderRoute: typeof GtrJoinRouteImport
      parentRoute: typeof GtrRouteRoute
    }
    '/gtr/login': {
      id: '/gtr/login'
      path: '/login'
      fullPath: '/gtr/login'
      preLoaderRoute: typeof GtrLoginRouteImport
      parentRoute: typeof GtrRouteRoute
    }
    '/gtr/organizer': {
      id: '/gtr/organizer'
      path: '/organizer'
      fullPath: '/gtr/organizer'
      preLoaderRoute: typeof GtrOrganizerRouteImport
      parentRoute: typeof GtrRouteRoute
    }
    '/gtr/v': {
      id: '/gtr/v'
      path: '/v'
      fullPath: '/gtr/v'
      preLoaderRoute: typeof GtrVRouteImport
      parentRoute: typeof GtrRouteRoute
    }
  }
}

interface GtrRouteRouteChildren {
  GtrScreenRoute: typeof GtrScreenRoute
  GtrJoinRoute: typeof GtrJoinRoute
  GtrLoginRoute: typeof GtrLoginRoute
  GtrOrganizerRoute: typeof GtrOrganizerRoute
  GtrVRoute: typeof GtrVRoute
  GtrIndexRoute: typeof GtrIndexRoute
}

const GtrRouteRouteChildren: GtrRouteRouteChildren = {
  GtrScreenRoute: GtrScreenRoute,
  GtrJoinRoute: GtrJoinRoute,
  GtrLoginRoute: GtrLoginRoute,
  GtrOrganizerRoute: GtrOrganizerRoute,
  GtrVRoute: GtrVRoute,
  GtrIndexRoute: GtrIndexRoute,
}

const GtrRouteRouteWithChildren = GtrRouteRoute._addFileChildren(
  GtrRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GtrRouteRoute: GtrRouteRouteWithChildren,
  ApiAfishaRoute: ApiAfishaRoute,
  ApiAfishaSendRoute: ApiAfishaSendRoute,
  ApiPosterRoute: ApiPosterRoute,
  ApiPushRoute: ApiPushRoute,
  ApiSprintReportRoute: ApiSprintReportRoute,
  ApiTgRoute: ApiTgRoute,
  ApiVphotoRoute: ApiVphotoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
