/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GtrRouteRouteImport } from './routes/gtr/route'
import { Route as ApiTgRouteImport } from './routes/api.tg'
import { Route as GtrIndexRouteImport } from './routes/gtr/index'
import { Route as GtrScreenRouteImport } from './routes/gtr/$screen'
import { Route as GtrJoinRouteImport } from './routes/gtr/join'
import { Route as GtrLoginRouteImport } from './routes/gtr/login'
import { Route as GtrOrganizerRouteImport } from './routes/gtr/organizer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GtrRouteRoute = GtrRouteRouteImport.update({
  id: '/gtr',
  path: '/gtr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTgRoute = ApiTgRouteImport.update({
  id: '/api/tg',
  path: '/api/tg',
  getParentRoute: () => rootRouteImport,
} as any)
const GtrIndexRoute = GtrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GtrRouteRoute,
} as any)
const GtrScreenRoute = GtrScreenRouteImport.update({
  id: '/$screen',
  path: '/$screen',
  getParentRoute: () => GtrRouteRoute,
} as any)
const GtrJoinRoute = GtrJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => GtrRouteRoute,
} as any)
const GtrLoginRoute = GtrLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GtrRouteRoute,
} as any)
const GtrOrganizerRoute = GtrOrganizerRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => GtrRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gtr': typeof GtrRouteRouteWithChildren
  '/api/tg': typeof ApiTgRoute
  '/gtr/$screen': typeof GtrScreenRoute
  '/gtr/join': typeof GtrJoinRoute
  '/gtr/login': typeof GtrLoginRoute
  '/gtr/organizer': typeof GtrOrganizerRoute
  '/gtr/': typeof GtrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/tg': typeof ApiTgRoute
  '/gtr/$screen': typeof GtrScreenRoute
  '/gtr/join': typeof GtrJoinRoute
  '/gtr/login': typeof GtrLoginRoute
  '/gtr/organizer': typeof GtrOrganizerRoute
  '/gtr': typeof GtrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gtr': typeof GtrRouteRouteWithChildren
  '/api/tg': typeof ApiTgRoute
  '/gtr/$screen': typeof GtrScreenRoute
  '/gtr/join': typeof GtrJoinRoute
  '/gtr/login': typeof GtrLoginRoute
  '/gtr/organizer': typeof GtrOrganizerRoute
  '/gtr/': typeof GtrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gtr'
    | '/api/tg'
    | '/gtr/$screen'
    | '/gtr/join'
    | '/gtr/login'
    | '/gtr/organizer'
    | '/gtr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/tg'
    | '/gtr/$screen'
    | '/gtr/join'
    | '/gtr/login'
    | '/gtr/organizer'
    | '/gtr'
  id:
    | '__root__'
    | '/'
    | '/gtr'
    | '/api/tg'
    | '/gtr/$screen'
    | '/gtr/join'
    | '/gtr/login'
    | '/gtr/organizer'
    | '/gtr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GtrRouteRoute: typeof GtrRouteRouteWithChildren
  ApiTgRoute: typeof ApiTgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gtr': {
      id: '/gtr'
      path: '/gtr'
      fullPath: '/gtr'
      preLoaderRoute: typeof GtrRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tg': {
      id: '/api/tg'
      path: '/api/tg'
      fullPath: '/api/tg'
      preLoaderRoute: typeof ApiTgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gtr/': {
      id: '/gtr/'
      path: '/'
      fullPath: '/gtr/'
      preLoaderRoute: typeof GtrIndexRouteImport
      parentRoute: typeof GtrRouteRoute
    }
    '/gtr/$screen': {
      id: '/gtr/$screen'
      path: '/$screen'
      fullPath: '/gtr/$screen'
      preLoaderRoute: typeof GtrScreenRouteImport
      parentRoute: typeof GtrRouteRoute
    }
    '/gtr/join': {
      id: '/gtr/join'
      path: '/join'
      fullPath: '/gtr/join'
      preLoaderRoute: typeof GtrJoinRouteImport
      parentRoute: typeof GtrRouteRoute
    }
    '/gtr/login': {
      id: '/gtr/login'
      path: '/login'
      fullPath: '/gtr/login'
      preLoaderRoute: typeof GtrLoginRouteImport
      parentRoute: typeof GtrRouteRoute
    }
    '/gtr/organizer': {
      id: '/gtr/organizer'
      path: '/organizer'
      fullPath: '/gtr/organizer'
      preLoaderRoute: typeof GtrOrganizerRouteImport
      parentRoute: typeof GtrRouteRoute
    }
  }
}

interface GtrRouteRouteChildren {
  GtrScreenRoute: typeof GtrScreenRoute
  GtrJoinRoute: typeof GtrJoinRoute
  GtrLoginRoute: typeof GtrLoginRoute
  GtrOrganizerRoute: typeof GtrOrganizerRoute
  GtrIndexRoute: typeof GtrIndexRoute
}

const GtrRouteRouteChildren: GtrRouteRouteChildren = {
  GtrScreenRoute: GtrScreenRoute,
  GtrJoinRoute: GtrJoinRoute,
  GtrLoginRoute: GtrLoginRoute,
  GtrOrganizerRoute: GtrOrganizerRoute,
  GtrIndexRoute: GtrIndexRoute,
}

const GtrRouteRouteWithChildren = GtrRouteRoute._addFileChildren(
  GtrRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GtrRouteRoute: GtrRouteRouteWithChildren,
  ApiTgRoute: ApiTgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
